ALTER TABLE POSTE DROP FOREIGN KEY poste_ibfk_1;
ALTER TABLE POSTE DROP FOREIGN KEY poste_ibfk_2;

ALTER TABLE INSTALLER DROP FOREIGN KEY unique_installation;
ALTER TABLE INSTALLER DROP FOREIGN KEY installer_ibfk_1;
ALTER TABLE INSTALLER DROP FOREIGN KEY installer_ibfk_2;
