- name: Installer Apache sur un serveur Red-Hat et démarrer le service
  hosts: localhost
  become: true
  tasks:
    - name: Installer Apache
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Démarrer le service Apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
