- name: Créer des utilisateurs
  hosts: localhost
  become: true
  vars:
    users:
      - name: user1
        password: "{{ lookup('env', 'password_user1') | password_hash('sha512') }}"
      - name: user2
        password: "{{ lookup('env', 'password_user2') | password_hash('sha512') }}"
      - name: user3
        password: "{{ lookup('env', 'password_user3') | password_hash('sha512') }}"
  tasks:
    - name: Ajouter plusieurs utilisateurs
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
      loop: "{{ users }}"
    
    - name: Création des groupes pour les utilisateurs
      ansible.builtin.group:
        name: "{{ item.name }}_group"
        state: present
      loop: "{{ users }}"
    
    - name: Ajouter les utilisateurs aux groupes correspondants
      ansible.builtin.user:
        name: "{{ item.name }}"
        groups: "{{ item.name }}_group"
        append: yes
      loop: "{{ users }}"
    
    - name: Créer un répertoire pour chaque utilisateur (avec les permissions appropriées)
      ansible.builtin.file:
        path: "/home/{{ item.name }}"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}_group"
        mode: '0755'
      loop: "{{ users }}"