ALTER TABLE INSTALLER
ADD CONSTRAINT unique_installation UNIQUE (nPoste, nLog);

ALTER TABLE INSTALLER
ADD CONSTRAINT fk_nPoste_installer
FOREIGN KEY (nPoste) REFERENCES POSTE(nPoste);

ALTER TABLE INSTALLER
ADD CONSTRAINT fk_nLog
FOREIGN KEY (nLog) REFERENCES LOGICIEL(nLog);

ALTER TABLE POSTE
ADD CONSTRAINT fk_indIP
FOREIGN KEY (indIP) REFERENCES SEGMENT(indIP);

ALTER TABLE POSTE
ADD CONSTRAINT fk_nSalle
FOREIGN KEY (nSalle) REFERENCES SALLE(nSalle);

ALTER TABLE POSTE
ADD CONSTRAINT fk_typePoste
FOREIGN KEY (typePoste) REFERENCES TYPES(typeLP);


ALTER TABLE SALLE
ADD CONSTRAINT fk_indIP
FOREIGN KEY (indIP) REFERENCES SEGMENT(indIP);


ALTER TABLE LOGICIEL
ADD CONSTRAINT fk_typeLog
FOREIGN KEY (typeLog) REFERENCES TYPES(typeLP);


