CREATE TABLE SOFTS AS SELECT nomLog, version, prix FROM LOGICIEL;
ALTER TABLE SOFTS CHANGE COLUMN nomLog nomSoft VARCHAR(20);
CREATE TABLE PCSEULS AS SELECT nPoste, nomPoste, indIP, ad, typePoste, nSalle FROM POSTE;
ALTER TABLE PCSEULS CHANGE COLUMN nPoste nP VARCHAR(7);
ALTER TABLE PCSEULS CHANGE COLUMN Poste nomP VARCHAR(20);
ALTER TABLE PCSEULS CHANGE COLUMN indIP seg VARCHAR(11);
ALTER TABLE PCSEULS CHANGE COLUMN typePoste typeP VARCHAR(9);
ALTER TABLE PCSEULS CHANGE COLUMN nSalle salle VARCHAR(7);
	
