SELECT typePoste FROM Poste WHERE nPoste = 'p8';
SELECT nomLog FROM Logiciel WHERE typeLog = 'UNIX';
SELECT nomSalle, CONCAT(Salle.indIP,'.',ad), Salle.nSalle FROM Salle,Poste WHERE Salle.nSalle = Poste.nSalle AND (typePoste = 'UNIX' OR typePoste = 'PCWS'); 
SELECT nLog FROM Installer WHERE nPoste = 'p6';
SELECT nPoste FROM Installer WHERE nLog = 'log1';
SELECT nomPoste, CONCAT(indIP,'.',ad) FROM Poste WHERE typePoste = 'TX';
SELECT nPoste, COUNT(nLog) FROM Installer GROUP BY (nPoste); 
SELECT nSalle, COUNT(nPoste) FROM Poste GROUP BY (nSalle);
SELECT nLog, COUNT(nPoste) FROM Installer GROUP BY (nLog);
SELECT AVG(prix) FROM Logiciel WHERE typeLog = 'UNIX';
SELECT MAX(dateAch) FROM Logiciel;
SELECT nPoste FROM Installer GROUP BY nPoste HAVING COUNT(nLog)=2; 
SELECT typeLP FROM Types WHERE typeLP NOT IN (SELECT typePoste FROM Poste);
SELECT typeLog FROM Logiciel WHERE typeLog IN (SELECT typePoste FROM Poste);
SELECT typePoste FROM Poste WHERE typePoste NOT IN (SELECT typeLog FROM Logiciel);
SELECT CONCAT(indIP,'.',ad) FROM Poste WHERE nPoste IN (SELECT nPoste FROM Installer WHERE nLog = 'log6');
SELECT CONCAT(indIP,'.',ad) FROM Poste WHERE nPoste IN (SELECT nPoste FROM Installer WHERE nLog = (SELECT nLog FROM Logiciel WHERE nomLog = 'Oracle 8'));
SELECT nomSegment FROM Segment WHERE indIP IN (SELECT indIP FROM Poste WHERE typePoste = 'TX' GROUP BY indIP HAVING COUNT(*)=3);
SELECT nomSalle FROM Salle WHERE nSalle IN (SELECT nSalle FROM Poste WHERE nPoste IN (SELECT nPoste FROM Installer WHERE nLog = (SELECT nLog FROM Logiciel WHERE nomLog = 'Oracle 6'))); 
SELECT nomLog FROM Logiciel WHERE dateAch = (SELECT MAX(dateAch) FROM Logiciel);