DELETE FROM SALLE WHERE indIP NOT IN (SELECT indIP FROM SEGMENT);
INSERT INTO TYPES (typeLP, nomType) VALUES ('BeOS', 'Système Be');
ALTER TABLE SALLE ADD CONSTRAINT fk_indIP FOREIGN KEY (indIP) REFERENCES SEGMENT(indIP);
ALTER TABLE LOGICIEL ADD CONSTRAINT fk_typeLog FOREIGN KEY (typeLog) REFERENCES TYPES(typeLP);
SELECT DISTINCT indIP FROM SALLE WHERE indIP NOT IN (SELECT indIP FROM SEGMENT);
SELECT DISTINCT typeLog FROM LOGICIEL WHERE typeLog NOT IN (SELECT typeLP FROM TYPES);
