- name: Installer Apache et démarrer le service
  hosts: localhost
  become: true
  tasks:
    - name: Installer Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Démarrer le service Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: yes
