version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    stdin_open: true  # Permet d'interagir avec le conteneur
    tty: true         # Active un terminal interactif
    entrypoint: bash  # Ouvre un shell bash par défaut
