version: "3.9"

services:

  ipa:
    image: freeipa/freeipa-server:rocky-9
    container_name: ipa_server
    hostname: ipa.lab.local
    privileged: true
    environment:
      IPA_SERVER_HOSTNAME: ipa.lab.local
      PASSWORD: adminpass
    networks:
      labnet:
        ipv4_address: 172.20.0.10
    ports:
      - "8080:80"
      - "8443:443"

  almalinux_srv:
    build: ./almalinux-server
    container_name: almalinux_srv
    hostname: srv.lab.local
    networks:
      labnet:
        ipv4_address: 172.20.0.11

  client1:
    build: ./fedora-client
    container_name: fedora_client1
    hostname: client1.lab.local
    networks:
      labnet:
        ipv4_address: 172.20.0.21

  client2:
    build: ./fedora-client
    container_name: fedora_client2
    hostname: client2.lab.local
    networks:
      labnet:
        ipv4_address: 172.20.0.22

networks:
  labnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24