version: '3'

services:
  in322:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - /home/florianandre/Documents/tp_linux:/bin223
    command: bash

